# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'laser_borders.ui'
#
# Created: Wed Dec 24 03:09:48 2014
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_laser_main(object):
    def setupUi(self, laser_main):
        laser_main.setObjectName(_fromUtf8("laser_main"))
        laser_main.resize(800, 600)
        self.centralwidget = QtGui.QWidget(laser_main)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.button_send = QtGui.QPushButton(self.centralwidget)
        self.button_send.setGeometry(QtCore.QRect(310, 420, 115, 31))
        self.button_send.setObjectName(_fromUtf8("button_send"))
        self.tl_x = QtGui.QDoubleSpinBox(self.centralwidget)
        self.tl_x.setGeometry(QtCore.QRect(120, 160, 77, 31))
        self.tl_x.setDecimals(3)
        self.tl_x.setMinimum(-1.0)
        self.tl_x.setMaximum(1.0)
        self.tl_x.setSingleStep(0.001)
        self.tl_x.setProperty("value", -1.0)
        self.tl_x.setObjectName(_fromUtf8("tl_x"))
        self.tl_y = QtGui.QDoubleSpinBox(self.centralwidget)
        self.tl_y.setGeometry(QtCore.QRect(240, 160, 77, 31))
        self.tl_y.setDecimals(3)
        self.tl_y.setMinimum(-1.0)
        self.tl_y.setMaximum(1.0)
        self.tl_y.setSingleStep(0.001)
        self.tl_y.setProperty("value", 1.0)
        self.tl_y.setObjectName(_fromUtf8("tl_y"))
        self.bl_x = QtGui.QDoubleSpinBox(self.centralwidget)
        self.bl_x.setGeometry(QtCore.QRect(120, 270, 77, 31))
        self.bl_x.setDecimals(3)
        self.bl_x.setMinimum(-1.0)
        self.bl_x.setMaximum(1.0)
        self.bl_x.setSingleStep(0.001)
        self.bl_x.setProperty("value", -1.0)
        self.bl_x.setObjectName(_fromUtf8("bl_x"))
        self.bl_y = QtGui.QDoubleSpinBox(self.centralwidget)
        self.bl_y.setGeometry(QtCore.QRect(240, 270, 77, 31))
        self.bl_y.setDecimals(3)
        self.bl_y.setMinimum(-1.0)
        self.bl_y.setMaximum(1.0)
        self.bl_y.setSingleStep(0.001)
        self.bl_y.setProperty("value", -1.0)
        self.bl_y.setObjectName(_fromUtf8("bl_y"))
        self.tr_x = QtGui.QDoubleSpinBox(self.centralwidget)
        self.tr_x.setGeometry(QtCore.QRect(430, 160, 77, 31))
        self.tr_x.setDecimals(3)
        self.tr_x.setMinimum(-1.0)
        self.tr_x.setMaximum(1.0)
        self.tr_x.setSingleStep(0.001)
        self.tr_x.setProperty("value", 1.0)
        self.tr_x.setObjectName(_fromUtf8("tr_x"))
        self.tr_y = QtGui.QDoubleSpinBox(self.centralwidget)
        self.tr_y.setGeometry(QtCore.QRect(560, 160, 77, 31))
        self.tr_y.setDecimals(3)
        self.tr_y.setMinimum(-1.0)
        self.tr_y.setMaximum(1.0)
        self.tr_y.setSingleStep(0.001)
        self.tr_y.setProperty("value", 1.0)
        self.tr_y.setObjectName(_fromUtf8("tr_y"))
        self.br_x = QtGui.QDoubleSpinBox(self.centralwidget)
        self.br_x.setGeometry(QtCore.QRect(430, 270, 77, 31))
        self.br_x.setDecimals(3)
        self.br_x.setMinimum(-1.0)
        self.br_x.setMaximum(1.0)
        self.br_x.setSingleStep(0.001)
        self.br_x.setProperty("value", 1.0)
        self.br_x.setObjectName(_fromUtf8("br_x"))
        self.br_y = QtGui.QDoubleSpinBox(self.centralwidget)
        self.br_y.setGeometry(QtCore.QRect(560, 270, 77, 31))
        self.br_y.setDecimals(3)
        self.br_y.setMinimum(-1.0)
        self.br_y.setMaximum(1.0)
        self.br_y.setSingleStep(0.001)
        self.br_y.setProperty("value", -1.0)
        self.br_y.setObjectName(_fromUtf8("br_y"))
        self.text_tl = QtGui.QLabel(self.centralwidget)
        self.text_tl.setGeometry(QtCore.QRect(180, 90, 80, 21))
        self.text_tl.setObjectName(_fromUtf8("text_tl"))
        self.text_tr = QtGui.QLabel(self.centralwidget)
        self.text_tr.setGeometry(QtCore.QRect(500, 90, 80, 21))
        self.text_tr.setObjectName(_fromUtf8("text_tr"))
        self.text_bl = QtGui.QLabel(self.centralwidget)
        self.text_bl.setGeometry(QtCore.QRect(159, 220, 111, 21))
        self.text_bl.setObjectName(_fromUtf8("text_bl"))
        self.text_br = QtGui.QLabel(self.centralwidget)
        self.text_br.setGeometry(QtCore.QRect(479, 220, 111, 21))
        self.text_br.setObjectName(_fromUtf8("text_br"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(150, 130, 80, 21))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(270, 130, 80, 21))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(580, 130, 80, 21))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(460, 130, 80, 21))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(270, 240, 80, 21))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(150, 240, 80, 21))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(580, 240, 80, 21))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(460, 240, 80, 21))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.edit_ip = QtGui.QLineEdit(self.centralwidget)
        self.edit_ip.setGeometry(QtCore.QRect(370, 20, 241, 31))
        self.edit_ip.setObjectName(_fromUtf8("edit_ip"))
        self.button_searchdac = QtGui.QPushButton(self.centralwidget)
        self.button_searchdac.setGeometry(QtCore.QRect(200, 20, 115, 31))
        self.button_searchdac.setObjectName(_fromUtf8("button_searchdac"))
        self.label_9 = QtGui.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(60, 320, 501, 31))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_10 = QtGui.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(110, 350, 491, 31))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        laser_main.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(laser_main)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 29))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        laser_main.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(laser_main)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        laser_main.setStatusBar(self.statusbar)

        self.retranslateUi(laser_main)
        QtCore.QObject.connect(self.tl_x, QtCore.SIGNAL(_fromUtf8("valueChanged(double)")), self.button_send.click)
        QtCore.QObject.connect(self.tl_y, QtCore.SIGNAL(_fromUtf8("valueChanged(double)")), self.button_send.click)
        QtCore.QObject.connect(self.tr_x, QtCore.SIGNAL(_fromUtf8("valueChanged(double)")), self.button_send.click)
        QtCore.QObject.connect(self.tr_y, QtCore.SIGNAL(_fromUtf8("valueChanged(double)")), self.button_send.click)
        QtCore.QObject.connect(self.bl_x, QtCore.SIGNAL(_fromUtf8("valueChanged(double)")), self.button_send.click)
        QtCore.QObject.connect(self.bl_y, QtCore.SIGNAL(_fromUtf8("valueChanged(double)")), self.button_send.click)
        QtCore.QObject.connect(self.br_x, QtCore.SIGNAL(_fromUtf8("valueChanged(double)")), self.button_send.click)
        QtCore.QObject.connect(self.br_y, QtCore.SIGNAL(_fromUtf8("valueChanged(double)")), self.button_send.click)
        QtCore.QMetaObject.connectSlotsByName(laser_main)

    def retranslateUi(self, laser_main):
        laser_main.setWindowTitle(QtGui.QApplication.translate("laser_main", "Laser geometry setter", None, QtGui.QApplication.UnicodeUTF8))
        self.button_send.setText(QtGui.QApplication.translate("laser_main", "Send Coords", None, QtGui.QApplication.UnicodeUTF8))
        self.text_tl.setText(QtGui.QApplication.translate("laser_main", "Top Left", None, QtGui.QApplication.UnicodeUTF8))
        self.text_tr.setText(QtGui.QApplication.translate("laser_main", "Top Right", None, QtGui.QApplication.UnicodeUTF8))
        self.text_bl.setText(QtGui.QApplication.translate("laser_main", "Bottom left", None, QtGui.QApplication.UnicodeUTF8))
        self.text_br.setText(QtGui.QApplication.translate("laser_main", "Bottom right", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("laser_main", "x", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("laser_main", "y", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("laser_main", "y", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("laser_main", "x", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("laser_main", "y", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("laser_main", "x", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("laser_main", "y", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("laser_main", "x", None, QtGui.QApplication.UnicodeUTF8))
        self.edit_ip.setText(QtGui.QApplication.translate("laser_main", "192.168.0.10", None, QtGui.QApplication.UnicodeUTF8))
        self.button_searchdac.setText(QtGui.QApplication.translate("laser_main", "Search DAC", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("laser_main", "Note: Messages will be sent when modifying the Spin Boxes", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("laser_main", "and when hitting \"Send Coords\" to the IP in the EditBox.", None, QtGui.QApplication.UnicodeUTF8))

